package com.mycompany.pro1p1_joselobo;

import javax.swing.JOptionPane;

/**
 *
 * @author rinal
 */
public class Menu extends javax.swing.JFrame {

    Labotifi_Code L = new Labotifi_Code();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Labotify = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        agregar1 = new javax.swing.JButton();
        agregar2 = new javax.swing.JButton();
        infoboton = new javax.swing.JButton();
        Modificarboton = new javax.swing.JButton();
        agregar5 = new javax.swing.JButton();
        Recursion = new javax.swing.JFrame();
        CrearLabo = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        albun = new javax.swing.JTextField();
        lanzamiento = new javax.swing.JTextField();
        artista = new javax.swing.JTextField();
        duracion = new javax.swing.JTextField();
        crear = new javax.swing.JButton();
        SalirCrearCancion = new javax.swing.JButton();
        Informacion = new javax.swing.JFrame();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        IdInfo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MostrarInformacion = new javax.swing.JTextArea();
        Lista = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaLista = new javax.swing.JTextArea();
        SalidaLista = new javax.swing.JButton();
        LaboEliminar = new javax.swing.JFrame();
        Eliminarid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        SalirEliminar = new javax.swing.JButton();
        ModificarCancion = new javax.swing.JFrame();
        nombre1 = new javax.swing.JTextField();
        albun1 = new javax.swing.JTextField();
        lanzamiento1 = new javax.swing.JTextField();
        artista1 = new javax.swing.JTextField();
        duracion1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        modificar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        SalirCrearCancion1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        idmodificar = new javax.swing.JTextField();
        Buscar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labotify = new javax.swing.JButton();
        recursion = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Labotify");

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        agregar1.setText("Eliminar");
        agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar1ActionPerformed(evt);
            }
        });

        agregar2.setText("Lista");
        agregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar2ActionPerformed(evt);
            }
        });

        infoboton.setText("Informacion");
        infoboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infobotonActionPerformed(evt);
            }
        });

        Modificarboton.setText("Modificar cancion");
        Modificarboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarbotonActionPerformed(evt);
            }
        });

        agregar5.setText("Menu");
        agregar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LabotifyLayout = new javax.swing.GroupLayout(Labotify.getContentPane());
        Labotify.getContentPane().setLayout(LabotifyLayout);
        LabotifyLayout.setHorizontalGroup(
            LabotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabotifyLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(LabotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Modificarboton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoboton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LabotifyLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        LabotifyLayout.setVerticalGroup(
            LabotifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabotifyLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(agregar)
                .addGap(18, 18, 18)
                .addComponent(agregar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregar2)
                .addGap(24, 24, 24)
                .addComponent(infoboton)
                .addGap(18, 18, 18)
                .addComponent(Modificarboton)
                .addGap(18, 18, 18)
                .addComponent(agregar5)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RecursionLayout = new javax.swing.GroupLayout(Recursion.getContentPane());
        Recursion.getContentPane().setLayout(RecursionLayout);
        RecursionLayout.setHorizontalGroup(
            RecursionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        RecursionLayout.setVerticalGroup(
            RecursionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Crear");

        jLabel4.setText("Nombre");

        jLabel5.setText("Albun");

        jLabel6.setText("Artista");

        jLabel7.setText("Año de lanzamiento");

        jLabel8.setText("Duracion en Segundos");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        albun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albunActionPerformed(evt);
            }
        });

        lanzamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanzamientoActionPerformed(evt);
            }
        });

        artista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistaActionPerformed(evt);
            }
        });

        duracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracionActionPerformed(evt);
            }
        });

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        SalirCrearCancion.setText("Salir");
        SalirCrearCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirCrearCancionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearLaboLayout = new javax.swing.GroupLayout(CrearLabo.getContentPane());
        CrearLabo.getContentPane().setLayout(CrearLaboLayout);
        CrearLaboLayout.setHorizontalGroup(
            CrearLaboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearLaboLayout.createSequentialGroup()
                .addGroup(CrearLaboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearLaboLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel3))
                    .addGroup(CrearLaboLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(CrearLaboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(albun, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(artista, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(lanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CrearLaboLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(crear)
                        .addGap(69, 69, 69)
                        .addComponent(SalirCrearCancion)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        CrearLaboLayout.setVerticalGroup(
            CrearLaboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearLaboLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(albun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(1, 1, 1)
                .addComponent(lanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CrearLaboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear)
                    .addComponent(SalirCrearCancion))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Informacion");

        jLabel13.setText("Id:");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        MostrarInformacion.setColumns(20);
        MostrarInformacion.setRows(5);
        jScrollPane2.setViewportView(MostrarInformacion);

        javax.swing.GroupLayout InformacionLayout = new javax.swing.GroupLayout(Informacion.getContentPane());
        Informacion.getContentPane().setLayout(InformacionLayout);
        InformacionLayout.setHorizontalGroup(
            InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformacionLayout.createSequentialGroup()
                .addGroup(InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InformacionLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel12))
                    .addGroup(InformacionLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(InformacionLayout.createSequentialGroup()
                                .addComponent(IdInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton2)
                                .addGap(32, 32, 32)
                                .addComponent(jButton3))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        InformacionLayout.setVerticalGroup(
            InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformacionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IdInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Lista");

        TextAreaLista.setColumns(20);
        TextAreaLista.setRows(5);
        jScrollPane1.setViewportView(TextAreaLista);

        SalidaLista.setText("Salir");
        SalidaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListaLayout = new javax.swing.GroupLayout(Lista.getContentPane());
        Lista.getContentPane().setLayout(ListaLayout);
        ListaLayout.setHorizontalGroup(
            ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaLayout.createSequentialGroup()
                .addGroup(ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListaLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel9))
                    .addGroup(ListaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ListaLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(SalidaLista)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        ListaLayout.setVerticalGroup(
            ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SalidaLista)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        Eliminarid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminaridActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Eliminar");

        jLabel11.setText("Ingrese la ID:");

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SalirEliminar.setText("Salir");
        SalirEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LaboEliminarLayout = new javax.swing.GroupLayout(LaboEliminar.getContentPane());
        LaboEliminar.getContentPane().setLayout(LaboEliminarLayout);
        LaboEliminarLayout.setHorizontalGroup(
            LaboEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LaboEliminarLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(LaboEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LaboEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Eliminarid, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(LaboEliminarLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(SalirEliminar)
                .addGap(53, 53, 53))
        );
        LaboEliminarLayout.setVerticalGroup(
            LaboEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LaboEliminarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Eliminarid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LaboEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalirEliminar)
                    .addComponent(jButton1))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre1ActionPerformed(evt);
            }
        });

        albun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albun1ActionPerformed(evt);
            }
        });

        lanzamiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanzamiento1ActionPerformed(evt);
            }
        });

        artista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artista1ActionPerformed(evt);
            }
        });

        duracion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracion1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Modificar Cancion");

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        jLabel15.setText("Nombre");

        SalirCrearCancion1.setText("Salir");
        SalirCrearCancion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirCrearCancion1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Albun");

        jLabel17.setText("Artista");

        jLabel18.setText("Año de lanzamiento");

        jLabel19.setText("Duracion en Segundos");

        jLabel20.setText("Id:");

        Buscar1.setText("Buscar");
        Buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModificarCancionLayout = new javax.swing.GroupLayout(ModificarCancion.getContentPane());
        ModificarCancion.getContentPane().setLayout(ModificarCancionLayout);
        ModificarCancionLayout.setHorizontalGroup(
            ModificarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarCancionLayout.createSequentialGroup()
                .addGroup(ModificarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarCancionLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(ModificarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(albun1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(artista1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(lanzamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(duracion1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ModificarCancionLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(modificar)
                                .addGap(69, 69, 69)
                                .addComponent(SalirCrearCancion1))
                            .addGroup(ModificarCancionLayout.createSequentialGroup()
                                .addComponent(idmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(Buscar1))
                            .addComponent(jLabel20)))
                    .addGroup(ModificarCancionLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel14)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        ModificarCancionLayout.setVerticalGroup(
            ModificarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarCancionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ModificarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(1, 1, 1)
                .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(2, 2, 2)
                .addComponent(albun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(1, 1, 1)
                .addComponent(lanzamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duracion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ModificarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificar)
                    .addComponent(SalirCrearCancion1))
                .addGap(38, 38, 38))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Menu");

        labotify.setText("Labotify");
        labotify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labotifyActionPerformed(evt);
            }
        });

        recursion.setText("Recursion");
        recursion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recursionActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(recursion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labotify, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(labotify)
                .addGap(41, 41, 41)
                .addComponent(recursion)
                .addGap(36, 36, 36)
                .addComponent(salir)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labotifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labotifyActionPerformed
        // TODO add your handling code here:
        Labotify.setVisible(true);
        Labotify.pack();
    }//GEN-LAST:event_labotifyActionPerformed

    private void recursionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recursionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recursionActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void agregar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar5ActionPerformed
        // TODO add your handling code here:
        Labotify.setVisible(false);
    }//GEN-LAST:event_agregar5ActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void albunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_albunActionPerformed

    private void lanzamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanzamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lanzamientoActionPerformed

    private void artistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artistaActionPerformed

    private void duracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracionActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        CrearLabo.setVisible(true);
        CrearLabo.pack();
    }//GEN-LAST:event_agregarActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:

        L.CrearCancion(nombre.getText(), albun.getText(), artista.getText(), Integer.parseInt(lanzamiento.getText()), Integer.parseInt(duracion.getText()));
        nombre.setText("");
        albun.setText("");
        artista.setText("");
        lanzamiento.setText("");
        duracion.setText("");
    }//GEN-LAST:event_crearActionPerformed

    private void SalirCrearCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirCrearCancionActionPerformed
        // TODO add your handling code here:
        CrearLabo.setVisible(false);
    }//GEN-LAST:event_SalirCrearCancionActionPerformed

    private void agregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar2ActionPerformed
        // TODO add your handling code here:
        Lista.setVisible(true);
        Lista.pack();
        TextAreaLista.setText(L.MandarLista());
    }//GEN-LAST:event_agregar2ActionPerformed

    private void SalidaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaListaActionPerformed
        // TODO add your handling code here:
        Lista.setVisible(false);
    }//GEN-LAST:event_SalidaListaActionPerformed

    private void infobotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infobotonActionPerformed
        // TODO add your handling code here:
        Informacion.setVisible(true);
        Informacion.pack();
    }//GEN-LAST:event_infobotonActionPerformed

    private void agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar1ActionPerformed
        // TODO add your handling code here:
        LaboEliminar.setVisible(true);
        LaboEliminar.pack();
    }//GEN-LAST:event_agregar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "Estas seguro que queres eliminar");
        if (JOptionPane.OK_OPTION == resp) {
            L.Eliminar(Integer.parseInt(Eliminarid.getText()));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EliminaridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminaridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminaridActionPerformed

    private void SalirEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirEliminarActionPerformed
        // TODO add your handling code here:
        LaboEliminar.setVisible(false);
    }//GEN-LAST:event_SalirEliminarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Informacion.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MostrarInformacion.setText(L.MostrarPropiedad(Integer.parseInt(IdInfo.getText())));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre1ActionPerformed

    private void albun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_albun1ActionPerformed

    private void lanzamiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanzamiento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lanzamiento1ActionPerformed

    private void artista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artista1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artista1ActionPerformed

    private void duracion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracion1ActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        L.ModificarDatos(nombre1.getText(), albun1.getText(), artista1.getText(), Integer.parseInt(lanzamiento1.getText()), Integer.parseInt(duracion1.getText()), Integer.parseInt(idmodificar.getText()));
    }//GEN-LAST:event_modificarActionPerformed

    private void SalirCrearCancion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirCrearCancion1ActionPerformed
        // TODO add your handling code here:
        ModificarCancion.setVisible(false);
    }//GEN-LAST:event_SalirCrearCancion1ActionPerformed

    private void Buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar1ActionPerformed
        // TODO add your handling code here:
        nombre1.setText(L.getCancion(Integer.parseInt(idmodificar.getText())));
        albun1.setText(L.getAlbun(Integer.parseInt(idmodificar.getText())));
        artista1.setText(L.getArtist(Integer.parseInt(idmodificar.getText())));
        lanzamiento1.setText(Integer.toString(L.getLanzamiento(Integer.parseInt(idmodificar.getText()))));
        duracion1.setText(Integer.toString(L.getDuracion(Integer.parseInt(idmodificar.getText()))));

    }//GEN-LAST:event_Buscar1ActionPerformed

    private void ModificarbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarbotonActionPerformed
        // TODO add your handling code here:
        ModificarCancion.setVisible(true);
        ModificarCancion.pack();
    }//GEN-LAST:event_ModificarbotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar1;
    private javax.swing.JFrame CrearLabo;
    private javax.swing.JTextField Eliminarid;
    private javax.swing.JTextField IdInfo;
    private javax.swing.JFrame Informacion;
    private javax.swing.JFrame LaboEliminar;
    private javax.swing.JFrame Labotify;
    private javax.swing.JFrame Lista;
    private javax.swing.JFrame ModificarCancion;
    private javax.swing.JButton Modificarboton;
    private javax.swing.JTextArea MostrarInformacion;
    private javax.swing.JFrame Recursion;
    private javax.swing.JButton SalidaLista;
    private javax.swing.JButton SalirCrearCancion;
    private javax.swing.JButton SalirCrearCancion1;
    private javax.swing.JButton SalirEliminar;
    private javax.swing.JTextArea TextAreaLista;
    private javax.swing.JButton agregar;
    private javax.swing.JButton agregar1;
    private javax.swing.JButton agregar2;
    private javax.swing.JButton agregar5;
    private javax.swing.JTextField albun;
    private javax.swing.JTextField albun1;
    private javax.swing.JTextField artista;
    private javax.swing.JTextField artista1;
    private javax.swing.JButton crear;
    private javax.swing.JTextField duracion;
    private javax.swing.JTextField duracion1;
    private javax.swing.JTextField idmodificar;
    private javax.swing.JButton infoboton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton labotify;
    private javax.swing.JTextField lanzamiento;
    private javax.swing.JTextField lanzamiento1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombre1;
    private javax.swing.JButton recursion;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
